name: Build and Test tcping

on:
  push:
    branches:
      - main
    paths:
      - 'tcping.c'
  pull_request:
    branches: [main]

jobs:
  macos-arm64:
    runs-on: macos-latest
    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 安装编译工具
      - name: Install Dependencies
        run: |
          brew update
          brew install gcc

      # 编译 tcping.c
      - name: Compile tcping
        run: |
          gcc -o tcping tcping.c

      # 测试编译结果
      - name: Test tcping
        run: |
          file tcping
