name: Build and Test tcping

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-arm64:
    runs-on: macos-latest
    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 编译 tcping.c
      - name: Compile tcping
        run: |
          gcc -o tcping tcping.c -lpthread
          echo "System Version: $(sw_vers -productVersion)"
          echo "Architecture: $(uname -m)"
      # 创建 DMG 包
      - name: Create DMG
        run: |
          # 创建临时目录
          mkdir -p tcping_dmg/tcping
          cp tcping tcping_dmg/tcping/
          
          # 创建 dmg 文件
          hdiutil create -volname tcping -srcfolder tcping_dmg/ -ov -format UDZO tcping-macos-arm64.dmg

      # 打包编译生成的文件
      - name: Package Binary
        run: |
          tar -czvf tcping-macos-arm64.tar.gz tcping
      # 上传 DMG Artifact
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tcping-macos-arm64
          path: tcping-macos-arm64.dmg

      - name: Upload TAR.GZ Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tcping-macos-arm64-tar
          path: tcping-macos-arm64.tar.gz
