name: Build and Test tcping

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-arm64:
    runs-on: macos-latest
    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 编译 tcping.c
      - name: Compile tcping
        run: |
          gcc -o tcping tcping.c -lpthread

      # 打包编译生成的文件
      - name: Package Binary
        run: |
          tar -czvf tcping-macos-arm64.tar.gz tcping

      # upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tcping-macos-arm64
          path: tcping-macos-arm64.tar.gz
