name: Build and Test tcping for ARM64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu-arm64-cross:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 安装交叉编译工具和 QEMU
      - name: Install Cross-Compile Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu build-essential

      # 使用交叉编译工具链编译为 ARM64
      - name: Compile for ARM64
        run: |
          aarch64-linux-gnu-gcc -o tcping tcping.c -lpthread
          cat /etc/os-release
          
      # 打包编译生成的文件
      - name: Package Binary
        run: |
          tar -czvf tcping-ubuntu-arm64.tar.gz tcping

      # 上传 Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tcping-ubuntu-arm64
          path: tcping-ubuntu-arm64.tar.gz
