name: Build and Test tcping

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu-arm64:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 安装依赖（确保 GCC 支持 ARM64 架构）
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # 设置为 ARM64 架构并编译 tcping.c
      - name: Compile tcping
        run: |
          gcc -o tcping tcping.c -lpthread

      # 打包编译生成的文件
      - name: Package Binary
        run: |
          tar -czvf tcping-ubuntu-arm64.tar.gz tcping

      # 上传 Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tcping-ubuntu-arm64
          path: tcping-ubuntu-arm64.tar.gz
