name: Build and Test tcping for ARM64

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu-arm64-native:
    runs-on: self-hosted
    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 安装编译工具
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # 编译为 ARM64 原生
      - name: Compile tcping
        run: |
          gcc -o tcping tcping.c -lpthread

      # 打包编译生成的文件
      - name: Package Binary
        run: |
          tar -czvf tcping-ubuntu-arm64.tar.gz tcping

      # 上传 Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tcping-ubuntu-arm64
          path: tcping-ubuntu-arm64.tar.gz
